### ISSUE TITLE
function fbRun()

### ISSUE THREAD

**Issue by santiag0m** [affromero/IBIO4680#2]
The code is taking corner patches from a horizontal concatenation of two images, for more than two images, the filter responses are only calculated for patches of the first and last images.

**Comment by affromero** [comment]
Could you please provide me more details (screenshot) or the output of your response? I do not completely get you.

**Comment by affromero** [comment]
Or if you suspect of any line of code that can cause this bug, I would really appreciate it if you point that out for me.

**Comment by santiag0m** [comment]
The second to last line, where the filtered image bank is indexed.

```
for i in range(np.array(fb).shape[0]):
		for j in range(np.array(fb).shape[1]):
			if fb[i][j].shape[0]<50:
				fim[i][j] = scipy.signal.convolve2d(impad, fb[i][j], 'same')
			else:
				fim[i][j] = fftconvolve(impad,fb[i][j])
			fim[i][j] = fim[i][j][r:-r,r:-r]
	return fim
```
